### ISSUE TITLE
Durable streams and catchup

### ISSUE THREAD

**Issue by gedw99** [omri86/longlived-grpc#2]
Nats Jetstream underneath would be maybe a nice match.

nats will push to the GRPC server instance and so no need for complex mutex aspects I am guessing.

nats Jetstream is also HA with each topic partitioned using RAFT and so a NATS node failure should in theory not interrupt anything 

the nats cli includes Jetstream and makes it easy to simulate messages pumping into nats and GRPC responding.

will be trying It out but figured it’s worth making an issue about it

**Comment by omri86** [comment]
Thanks for the idea but the purpose of this repo is a pure gRPC client & server example for long lived streaming,
hence I wish to avoid adding 3rd parties to this project at this moment.
